server:
  port: 3000
database:
  connection_string: mongodb://root:password@0.0.0.0:27017/
token:
  key: ""
sqs:
  endpoint: "http://localhost:4566"
  region: sa-east-1
  clock_in_queue: http://sqs.sa-east-1.localhost.localstack.cloud:4566/000000000000/clock_in_register
  report_queue: http://sqs.sa-east-1.localhost.localstack.cloud:4566/000000000000/month_report_requests