@startuml

frame "Kubernetes" {
    component "Register" <<Service>> as registro
    component "Authentication" <<Service>> as auth
}

queue "SQS" {
    queue registers
}

database "RDS"{
    database "DB PostgreSQL Register Replica" {
        folder "Registros de Ponto" <<table>> as tbregistrosreplica
    }

    database "DB PostgreSQL Register" {
        folder "Registros de Ponto" <<table>> as tbregistros
        folder "Actions" <<table>> as actions
    }

    database "DB PostgreSQL User" {
        folder "Usuários" <<table>> as tbusers
    }
}

auth --> tbusers
registro -> registers
registers ...> registro
registro --> tbregistros : inserts/updates
registro -> actions
tbregistrosreplica <- registro : reads

@enduml