name: cd_workflow
on:
  push:
    branches:
      - master







name: Build, Push and Deploy
on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths-ignore:
      - '**/README.md'
      - 'deployments/**'
jobs:
  build_test_push:
      name: Build and run unit/functional tests
      needs: version_and_release
      runs-on: ubuntu-latest
      permissions:
        packages: write
        contents: read
      env:
        CFG_SERVER_HTTP_PORT: 8080

      steps: 
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.4

      - name: Checkout branch of current repository
        uses: actions/checkout@v2
        with:
          path: ./service

      - name: Go vet
        working-directory: ./service
        run:
          go vet ./...
          
      - name: Unit test
        working-directory: ./service
        run:
          go test ./...

      - name: Go build for Docker
        working-directory: ./service
        run: cd cmd/service && CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -a -tags netgo -ldflags '-w' -o $GITHUB_WORKSPACE/dist/build/service

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: service/build/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{needs.version_and_release.outputs.version}}

  deploy:
      name: Deploy
      needs: [build_test_push, version_and_release]
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0

      - name: Update container image tag
        run: sed -i 's|ghcr.io/${{ github.repository }}[^"]*|ghcr.io/${{ github.repository }}:${{needs.version_and_release.outputs.version}}|' deployments/manifest.yaml

      - name: Apply manifest
        uses: notnull-co/kubectl-action@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBECONFIG }}
        with:
          args: kubectl apply -f deployments/manifest.yaml

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.9.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          commit_message: Automatic Commit - Updated image version to ${{needs.version_and_release.outputs.version}}

