name: ci_workflow
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get ./...
      - name: Build
        run: CGO_ENABLED=0 go build -v -o dist/hackaton cmd/client/main.go